### ISSUE TITLE
Add missing Skulpt Processing functions

### ISSUE THREAD

**Issue by tildebyte** [Calysto/calysto#5] opened 2015-03-18 17:45 UTC
Which Processing version is implemented? Are you leveraging p5.js? I ask because I'm seeing e.g. `uncaught exception: NameError: name 'bezier' is not defined on line 12` where I would expect `bezier()` to be implemented.

**Comment by dsblank** [comment] 2015-03-18 17:47
The Processing used is Processing.js... I believe that I have used bezier... let me check...

**Comment by dsblank** [comment] 2015-03-18 18:00
bezier worked for me here:

http://jupyter.cs.brynmawr.edu/hub/dblank/public/CS110%20Intro%20to%20Computing/2015/Lectures/Visualization2.ipynb#1.3-Genomics

How are you getting an error with a line number? Are you sure you are running the Processing kernel?

**Comment by tildebyte** [comment] 2015-03-18 18:10
Duh... If I had actually *read* the readme...
The error is from Firefox' JS console.
I'm not sure what you're asking... I'm running skulpt-kern... Oh.
Oops. Should have specified that it's the skulpt kernel >_<

**Comment by dsblank** [comment] 2015-03-18 18:16
Oh, right... I pointed you to a Processing notebook... looks like Skulpt Processing doesn't have bezier hooked up... should be easy to add. They said that there would be things missing. Please make a list of missing things in Skulpt Processing, and I'll see if we can add.

BTW, one of the bugs in the current code is that only the last Skulpt canvas gets the mouse controls. Need to look into that...

**Comment by tildebyte** [comment] 2015-03-18 18:33
Cool, will do.
What's the likelihood of "upgrading" to p5.js?

**Comment by dsblank** [comment] 2015-03-18 18:49
On Wed, Mar 18, 2015 at 2:33 PM, tildebyte <notifications@github.com> wrote:

> Cool, will do.
> What's the likelihood of "upgrading" to p5.js?
>

That isn't easy, unfortunately (I haven't looked into it in detail though,
so the following may be wrong). The wrapper to connect a Javascript library
to Skulpt Python looks like it has to be done by hand (which is why some
things like bezier are missing).

A nice project would read a Javascript lib, and automatically connect it to
Skulpt.

But, if you want to have a look at what is necessary, check out how they do
it here:

https://github.com/skulpt/skulpt/tree/master/src/lib

**Comment by tildebyte** [comment] 2015-03-18 18:59
Ah, yes. I remember looking at that when I first heard about Skulpt. I was bashing my head against making the Processing external library work when I realized the same thing you did - it's a *lot* of painstaking work, and probably left to someone who knows what they're doing (e.g. not me).

**Comment by dsblank** [comment] 2015-03-19 09:27
Actually, it isn't too bad; I just made a pull request to add bezier to Skulpt... let's see how I did.

https://github.com/skulpt/skulpt/pull/359

If you were interested, the next step is to compare:

http://processingjs.org/reference/

with:

https://github.com/skulpt/skulpt/blob/master/src/lib/processing/__init__.js

and see what is missing. Then, little wrappers need to be written like bezier (or if we get some feedback on the PR).

**Comment by dsblank** [comment] 2015-03-19 10:01
Ok, bezier was merged, and we have the :+1: to list what is missing, and write the stubs. If anyone would like to help with this task, please let me know.

**Comment by tildebyte** [comment] 2015-03-19 13:57
Assumption: **Everything** [listed](http://processingjs.org/reference) under "Environment", "Data", and "Control" is part of JS, not Processing.js per-se. **Parts** of "Structure" are JS, parts are Processing.js. 
I'm not sure about all of "Data/String Functions".
I'm not that familiar with JS, so I don't know which parts of "Math" come from it, and which are Processing.js.

**Comment by tildebyte** [comment] 2015-03-19 14:25
A completely brain-dead [list](https://gist.github.com/tildebyte/7a51a961c23c57967abd) of Processing.js functions not yet implemented.

**Comment by dsblank** [comment] 2015-03-19 14:47
Great, perfect! Do you want to try adding some of these to Skulpt? Or you could make a PR off of my fork first? Or do you want to leave that to others to now implement?

**Comment by tildebyte** [comment] 2015-03-19 14:52
I think my role here is more secretarial ;)
I'm not much of a JavaScripter (not at all, if I'm honest). However, if there's any *Python*… :thumbsup:

**Comment by dsblank** [comment] 2015-03-19 14:55
No problem... that list is already a good start. Often, that is the step that is hardest to take. Now, we just need to fill in the details. I'll report back here when complete, and then we'll close this issue.

**Comment by dsblank** [comment] 2015-03-24 03:41
Finally able to test bezier thanks to new docs at Skulpt. Here's a peek:

![screenshot from 2015-03-23 23 38 55](https://cloud.githubusercontent.com/assets/168568/6795427/f5916d66-d1b5-11e4-9619-bc78c7080842.png)

Now I feel confident that we can test the rest of the Skulpt Processing API as it is added.

**Comment by tildebyte** [comment] 2015-03-24 03:42
Nice! I'm interested in helping out.

**Comment by dsblank** [comment] 2015-03-24 03:45
Should be the case that you can update and install the latest calysto from git, and you should have the new bezier function in the Skulpt Python kernel.

**Comment by dsblank** [comment] 2015-03-26 02:23
Most of the missing ProcessingJS bridge has been added to my repo, and a PR has been made:

https://github.com/skulpt/skulpt/pull/366

It should be the case that one can replicate most of ProcessingJS, given these changes:

* I think most code should be in setup() or draw()
* requires run()
* some names were changed:
  * frameRate is only a function, not a variable: see getFrameRate()
  * Use getMousePressed() rather than mousePressed
  * Use getKeyPressed() rather than keyPressed
  * Use width() rather than width
  * use height() rather than height
  * Use mouseX() rather than mouseX
  * Use mouseY() rather than mouseY
  * Use pmouseX() rather than pmouseX
  * Use pmouseY() rather than pmouseY

There may be some missing constants that you need. Please report if so.

**Comment by tildebyte** [comment] 2015-03-26 14:29
Forgive my abysmal ignorance (still getting my footing with Jupyter/Calysto), but what's the easiest way to get your dev processing.js into a Jupyter server for testing purposes? I've been pulling Calysto in successfully, but I'm not sure about P5.js, as it's hosted externally (I think?). Is the hosted version your latest?

**Comment by dsblank** [comment] 2015-03-26 15:18
I think that this is the easiest, for now (will update pip soon):

1. Install IPython 3 from standard means (anaconda, pip, etc)
2. Install metakernel: sudo pip install metakernel
3. Clone calysto from git, and "sudo python setup.py install"
4. Install the Skulpt kernel: sudo pip install skulpt-python

The current Skulpt kernel is using my PR Skulpt Javascript code, so it should just work. 

Let me know if you have any problems.

**Comment by dsblank** [comment] 2015-03-26 15:37
Actually, I should give you an account on http://jupyter.cs.brynmawr.edu and you can use it directly. Send me email at doug.blank@gmail.com if you would like to try that option.

**Comment by dsblank** [comment] 2015-03-26 16:21
With the latest Skulpt changes, the following are also possible:

1. Use mouseX() or mouse.x rather than mouseX
1. Use mouseY() or mouse.y rather than mouseY
1. Use pmouseX() or mouse.px rather than pmouseX
1. Use pmouseY() or mouse.py rather than pmouseY
1. Use environment.frameCount
1. Use environment.width or screen.width
1. Use environment.height or screen.height

**Comment by tildebyte** [comment] 2015-03-26 18:38
This might be slightly off-topic, but...
Since we're in roughly the same weird intersection between a low-level Processing implementation and a Python wrapper *primarily for pedagogical purposes*, it might be a good idea to talk to [jdf](https://github.com/jdf) over at [Processing.py](https://github.com/jdf/processing.py#python-mode-for-processing). He's already faced some thorny issues regarding whether or not Python or P5/Java should win the day in some instances (i.e. globals (Python), the conflicting `map` functions (P5)).

**Comment by dsblank** [comment] 2015-03-26 19:34
Sure, no problem! Generally, I have helped get such projects working, and help find people interested in working on them. I spend my time on those that I think should win the day for my purposes, but understand that there are many different goals and different communities. 

Having said that, there have been some decisions made in the Processing language that I would not have made :) Processing-map is a great little tool, but "map" is not necessarily a good name. Of course, "from processing import *" is an easy way to get started, but can cause havoc. Then one has to weigh the costs of deviating from the "Processing standard" in order to avoid overwriting random and map...

**Comment by juliendorra** [comment] 2015-03-26 22:22
Python Mode in the Processing IDE is great, and constantly improved since we started  using it for our creative coding workshop with kids (https://github.com/juliendorra/cookies-code-couleurs).
It would indeed be great if there was the possibility of using the same solutions / choices in both ProcessingJS+Skulpt and Python Mode in Processing IDE.

Not sure how feasible it is…

**Comment by dsblank** [comment] 2015-03-26 23:03
@juliendorra We can certainly try to make the same choices. Are the differences between Processing Python-mode and Processing enumerated (eg, things like mouseX, keyPressed, etc)? I couldn't find a list of differences.

**Comment by dsblank** [comment] 2015-03-26 23:07
I've got some work to do... many of the newly added functions are not correct... I have misunderstood how arguments work. Hopefully will have fixes this evening...

**Comment by dsblank** [comment] 2015-03-26 23:58
Ok, things are looking much better. Now, to make some notebooks that test every single function...

**Comment by tildebyte** [comment] 2015-03-27 00:34
To the best of my recollection, most things in P5.py have gone the Processing way. A couple of exceptions off the top of my head are hex color specifications (`#` is a comment marker in Python after all) and globals (they work as in Python, not Java). OTOH, imports are done as e.g. `add_library('foo')`.

**Comment by tildebyte** [comment] 2015-03-27 16:06
From the examples:
- Ints and floats (because Python)
- `with` is implemented for a number of things (pushStyle, pushMatrix, beginContour, beginShape, beginClosedShape) e.g.:

````python
    with pushMatrix():
        translate(10, 10)
        rotate(PI/3)
        rect(0, 0, 10, 10)
    rect(0, 0, 10, 10)
````

**Comment by dsblank** [comment] 2015-03-27 16:13
The `with` use is clever, but I doubt that Skulpt has support for that.
Need to check...

**Comment by tildebyte** [comment] 2015-03-27 16:15
I love it, if only for sheer readability.

**Comment by tildebyte** [comment] 2015-03-27 16:17
Shoot. Are we missing `PVector`?

**Comment by dsblank** [comment] 2015-03-27 16:26
There are 4 classes that need to added:

    //mod.PFont = Sk.misceval.buildClass(mod, fontClass, "PFont", []);
    //mod.PGraphics = Sk.misceval.buildClass(mod, graphicsClass,
"PGraphics", []);
    //mod.PShape = Sk.misceval.buildClass(mod, shapeClass, "PShape", []);
    //mod.PVector = Sk.misceval.buildClass(mod, vectorClass, "PVector", []);

As soon as I get that figured out, I'll add them. My final goal is to be
100% compatible with ProcessingJS.

**Comment by tildebyte** [comment] 2015-03-27 17:38
There seems to be an issue with `dist()`. Running the second sketch (BouncyBubbles) in [Motion.ipynb](http://jupyter.cs.brynmawr.edu/user/benalkov/notebooks/Motion.ipynb), I get `uncaught exception: ExternalError: TypeError: a is undefined on line 27`. Switch out lines 27 and 28 (to do the math "manually") and the sketch works as expected.

**Comment by dsblank** [comment] 2015-03-27 20:38
dist() has been fixed. Thanks!

**Comment by dsblank** [comment] 2015-03-30 12:30
PVector has been added. skulpt_python kernel is now in its own repo: https://github.com/Calysto/skulpt_python

PVector (and all changes mentioned here) are in a PR to the main https://github.com/skulpt/skulpt repo.

**Comment by tildebyte** [comment] 2015-04-02 16:21
I'm seeing something weird here.

This works:

````py
from processing import *

def setup():
    noLoop()
    
def draw():
    vec = PVector(40, 20)
    ellipse(vec.x, vec.y, 12, 12)

run()
````
This does not (throws `NameError: name 'Pvector' is not defined`):

````py
from processing import *

class KochLine(object):

    def __init__(self):
        self.vec = Pvector()
#       Also
#         self.vec = Pvector(0, 0, 0)

def setup():
    k = KochLine()

def draw():
    pass

run()

**Comment by dsblank** [comment] 2015-04-02 16:24
It is PVector (capital V).

**Comment by tildebyte** [comment] 2015-04-02 16:37
::sigh::

**Comment by tildebyte** [comment] 2015-04-04 21:02
Do you want to continue tracking issues here, or should I open new issues as I find things?

**Comment by dsblank** [comment] 2015-04-05 00:03
You can list them here. Thanks!

**Comment by tildebyte** [comment] 2015-04-07 16:22
This:

````py
from processing import *

c1 = color(0, 0, 0, 255)

````

yields `ExternalError: TypeError: mod.processing is null on line 3`

I see a note in the PR at skulpt regarding adding `color`, so I'm wondering if the hosted script is out-of-date...

**Comment by tildebyte** [comment] 2015-04-07 18:36
`ExternalError: TypeError: modelView.rotateY is not a function on line 14`

**Comment by dsblank** [comment] 2015-04-07 19:15
On Tue, Apr 7, 2015 at 12:22 PM, tildebyte <notifications@github.com> wrote:

> This:
>
> from processing import *
>
> c1 = color(0, 0, 0, 255)
>
> yields ExternalError: TypeError: mod.processing is null on line 3
>

This error looks like color() has been called before run() has been
executed. I think that this could be fixed with a deeper fix, but this is
how it currently works (if I understand the error).

**Comment by dsblank** [comment] 2015-04-07 19:21
On Tue, Apr 7, 2015 at 2:36 PM, tildebyte <notifications@github.com> wrote:

> ExternalError: TypeError: modelView.rotateY is not a function on line 14
>

Looks like rotateX() and rotateY() have to be inside draw(). Again, this is
how it was designed. Requests to make that more robust should probably be
made at skulpt.

**Comment by tildebyte** [comment] 2015-04-07 20:10
I'm starting to think I need a holiday.

Processing/Processing.py both allow most things to occur outside of `setup` and `draw`, and that's a hard habit to break.

Looks like, after I installed the latest updates, and made certain that everything relevant is inside `setup`/`draw`, `color` is fine.

`rotate()` et al. require the `WEBGL` arg to `setup()`

**Comment by dsblank** [comment] 2015-04-07 20:40
On Tue, Apr 7, 2015 at 4:10 PM, tildebyte <notifications@github.com> wrote:

> I'm starting to think I need a holiday.
>
> Processing/Processing.py both allow most things to occur outside of setup
> and draw, and that's a hard habit to break.
>

I agree, and think that we should report that, and fix in a separate PR.


> Looks like, after I installed the latest updates, and made certain that
> everything relevant is inside setup/draw, color is fine.
>

Goos, at least it works as it was designed. We just need to fix the design.


> rotate() et al. require the WEBGL arg to setup()
>

Yep.

Thanks!

**Comment by tildebyte** [comment] 2015-04-10 17:32
````py
from processing import *

def setup():
    size(512, 512, WEBGL)
    
def draw():
    rect(screen.width / 2, screen.height / 2, 100, 100)

run()
````

Gives me `uncaught exception: ExternalError: rect() with rounded corners is not supported in 3D mode on line 10`. Using the default renderer (no `WEBGL`) works fine.

**Comment by dsblank** [comment] 2015-04-10 17:39
@tildebyte So, it sounds like the default for rect is wrong? Does the no-WEBGL rect have rounded corners? Does the ProcessingJS version of this same code work? Or is it their bug?

**Comment by tildebyte** [comment] 2015-04-10 21:53
No, it's square with the default renderer. I'll have to figure out how to test under P5js.

**Comment by dsblank** [comment] 2015-04-11 21:15
@tildebyte Ah, found the issue with rect() in WEBGL... good find! You must be testing lots of variations.

**Comment by tildebyte** [comment] 2015-04-11 21:57
Amusingly enough, I just seem to be... lucky? in the examples I've picked :)

**Comment by dsblank** [comment] 2015-04-11 22:05
All known issues fixed. Time to find some bugs! In 24 hours, I'll submit the PR for merging, and close this issue. Future finds will go over to Skulpt.

**Comment by tildebyte** [comment] 2015-04-11 22:07
Awesome.
So, we should start opening issues against Skulpt?

**Comment by dsblank** [comment] 2015-04-11 22:09
You can report them here until we close this.

**Comment by tildebyte** [comment] 2015-04-11 22:25
Hmm...
[This](http://jupyter.cs.brynmawr.edu/user/benalkov/notebooks/Demos/Graphics.ipynb) sketch should look like [this](https://ello.co/quaestor/post/KrEvkCByAqEx8SldADVHJg) animated GIF.
The code is as close as I can make it. The only differences are the Skulpt/P5js-isms and the code used for the ello post has slightly different parameters, to allow it to loop much more quickly (note, however, that the GIF doesn't loop properly in Firefox >_>).
I'm not getting any warnings or errors.

**Comment by dsblank** [comment] 2015-04-11 22:37
You have to publish a notebook before it can be viewed by others... just
click the link button, and grab that URL.

**Comment by tildebyte** [comment] 2015-04-11 22:50
Ah, understood.
http://jupyter.cs.brynmawr.edu/hub/benalkov/public/Graphics.ipynb

**Comment by dsblank** [comment] 2015-04-12 00:10
Any idea what the problem is with that example?

**Comment by tildebyte** [comment] 2015-04-12 02:19
I just don't even know... TBH, my understanding of the math is pretty minimal. Everything else is pretty straightforward.
AFAICT, it's like it's being drawn in 2D, or something. 1 segment doesn't show up; 2 move up and down; 3 float around a bit, but only in a plane.
The 2D renderers don't work, of course. I've tried `P3D`, `WEBGL`, and `OPENGL`, and they all draw the same way, although they behave slightly differently (`OPENGL` flickers *a lot*).

**Comment by dsblank** [comment] 2015-04-13 12:31
Ok, this PR has been merged. Any issue/PR should be made over there:

https://github.com/skulpt/skulpt

Thanks! More testing needed, of course.

**Closed by dsblank** 2015-04-13 12:31 UTC
